### ISSUE TITLE
SENG 360 adding to schedule causes Application Error

### ISSUE THREAD

**Issue by JC-02** [tanujdargan/uvic-coursemap#6]
Anytime I go to add SENG 360 to a timetable, when I select it the application crashes and provides the following error:
![image](https://github.com/user-attachments/assets/db2b09bc-7470-4477-975d-acf2d4238e03)

Here is the browser console information as well:
![image](https://github.com/user-attachments/assets/8881bd22-a442-44a0-bb4b-378588830c7f)

I haven't seen this come up with most other courses I tried (experimented with more to try and replicate), and it seems to occur in every browser I have tried. No big deal just something you could look into if you wanted or think it's an easy fix.

**Comment by tanujdargan** [comment]
Hi @JC-02 thank you for bringing this to my attention.

This error occurs because some sections of SENG 360, specifically the section with CRN 14229, have undefined days or time fields. Our application wasn't handling sections without defined days or time, which led to the crash.

Root Cause:
Undefined days or time: The course data contains sections where days or time are undefined.
Assumption in Code: The generateCalendarEvents function in calendarUtils.ts assumed that all sections have valid days and time values.

Unhandled Case: When the function tried to perform operations (like .replace()) on an undefined value, it resulted in a TypeError.

Solution:
I've updated the generateCalendarEvents function to handle cases where days or time might be undefined. The function now checks for the existence of these fields before processing them. If either days or time is missing, the section is skipped, and a warning is logged.

Updated code can be found in the following commit: https://github.com/tanujdargan/uvic-coursemap/commit/03a5bf9a74f5159bd7262c2165851ab1b607b186

The fix is live and I would request you to test it out for yourself. If you do face any other issues please let me know!
